%%
%% Autogenerated by Thrift Compiler (0.8.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(kestrel_types).

-include("kestrel_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('item') ->
  {struct, [{1, string}, {2, i64}]}
;

struct_info('queueInfo') ->
  {struct, [{1, string}, {2, i64}, {3, i64}, {4, i64}, {5, i64}, {6, i32}, {7, i32}]}
;

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('item') ->
  {struct, [{1, undefined, string, 'data', undefined}, {2, undefined, i64, 'id', undefined}]}
;

struct_info_ext('queueInfo') ->
  {struct, [{1, optional, string, 'head_item', undefined}, {2, undefined, i64, 'items', undefined}, {3, undefined, i64, 'bytes', undefined}, {4, undefined, i64, 'journal_bytes', undefined}, {5, undefined, i64, 'age', undefined}, {6, undefined, i32, 'waiters', undefined}, {7, undefined, i32, 'open_transactions', undefined}]}
;

struct_info_ext('i am a dummy struct') -> undefined.

